Adding columns for: units, dividends, PnL
PhracturedBlue/fava-portfolio-summary pull request #2
Opened 2022-03-30 10:38 UTC by p-oz

Added some code to include columns for UNITs, Dividends and PnL and also to handle multiple cash accounts with different currencies

2022-03-30 13:54 UTC, PhracturedBlue requested changes
Please run pylint on the code and fix all issues.

2022-03-30 13:54 UTC, PhracturedBlue commented on __init__.py
> +        elif self.other_currencies[0] in balance and self.other_currencies[0] in cost:
self.other_currencies could be an empty set, you can't always access element 0 from it

2022-03-30 13:54 UTC, PhracturedBlue commented on templates/PortfolioSummary.html
> -  {% set types = data[0] %}
please don't change the indentation.  It makes it harder to review and run 'git annotate' on.  Also, I liked it the way it was

2022-03-30 13:54 UTC, PhracturedBlue commented on __init__.py
> +
Please remove all trailing whitespace.

2022-04-07 10:58 UTC, p-oz commented
Done and fixed

2022-04-07 13:05 UTC, PhracturedBlue commented
Thanks, Merged

2022-04-07 13:05 UTC, closed without merging